--- 
-
  vars:
    local_user: "{{ ansible_user_id }}"
    homedir: "/home/{{ local_user }}"
    dotfiles:
      local: "{{ homedir }}/.dotfiles-local"
      dest: "{{ homedir }}/.dotfiles"
      repo: git@github.com:hjhart/dotfiles.git 

  hosts: localhost
  tasks:
    - include: tasks/smbshares.yml
    - include: tasks/plex.yml
    - include: tasks/rubies.yml
    - include: tasks/git_config.yml
    - include: tasks/dotfiles.yml
    - include: tasks/vim.yml
