---
- name: Install rbenv
  apt: 
    name: rbenv
    state: present
  become: true   
  
- name: install ruby-build
  apt: 
    name: ruby-build
    state: present
  become: true   

- name: register installed rubies
  register: ruby_installed
  command: rbenv versions | grep 2.2.3
  ignore_errors: true

- name: install most recent version of ruby
  command: rbenv install 2.2.3
  when: ruby_installed|failed
